TYPE=VIEW
query=select `stap`.`studentCode` AS `studentCode`,`stap`.`nameTh` AS `nameTh`,`stap`.`surnameTh` AS `surnameTh`,`stap`.`nameEn` AS `nameEn`,`stap`.`surnameEn` AS `surnameEn`,`stap`.`programCode` AS `programCode`,`stap`.`programNameTh` AS `programNameTh`,`stap`.`programNameEn` AS `programNameEn`,`stap`.`facultyID` AS `facultyID`,`stap`.`facultyNameTh` AS `facultyNameTh`,`stap`.`facultyNameEn` AS `facultyNameEn`,`stap`.`levelNameSTh` AS `levelNameSTh`,`stap`.`levelNameSEn` AS `levelNameSEn`,`stap`.`levelID` AS `levelID`,`stap`.`levelName` AS `levelName`,`stap`.`admitAcadYear` AS `admitAcadYear`,`stap`.`status` AS `status`,`stap`.`statusName` AS `statusName`,`stap`.`gender` AS `gender`,`stap`.`graduateDate` AS `graduateDate`,`stap`.`citizenID` AS `citizenID`,`stap`.`std_api_update` AS `std_api_update`,`stap`.`std_api_status` AS `std_api_status`,`stst`.`std_studentCode` AS `std_studentCode`,`stst`.`std_prenameTh` AS `std_prenameTh`,`stst`.`std_nameTh` AS `std_nameTh`,`stst`.`std_surnameTh` AS `std_surnameTh`,`stst`.`std_programNameTh` AS `std_programNameTh`,`stst`.`std_facultyNameTh` AS `std_facultyNameTh`,`stst`.`std_levelNameSTh` AS `std_levelNameSTh`,`stst`.`std_mobilephone` AS `std_mobilephone`,`stst`.`std_address` AS `std_address`,`stst`.`std_subdistrict` AS `std_subdistrict`,`stst`.`std_district` AS `std_district`,`stst`.`std_province` AS `std_province`,`stst`.`std_zip` AS `std_zip`,`stst`.`std_homephone` AS `std_homephone`,`stst`.`std_homeprovinceid` AS `std_homeprovinceid`,`stst`.`std_update` AS `std_update`,`stst`.`std_status` AS `std_status` from (`alumni`.`student_api` `stap` join `alumni`.`student_std` `stst` on(`stst`.`std_studentCode` = `stap`.`studentCode`)) group by `stap`.`studentCode` order by `stap`.`studentCode` desc
md5=754f85ddccd79fb3abeaa38c4c8db21c
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-10-05 09:28:56
create-version=2
source=Select\n    *\nFrom\n    student_api stap Inner Join\n    student_std stst On stst.std_studentCode = stap.studentCode\nGroup By\n    stap.studentCode\nOrder By\n    stap.studentCode Desc
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `stap`.`studentCode` AS `studentCode`,`stap`.`nameTh` AS `nameTh`,`stap`.`surnameTh` AS `surnameTh`,`stap`.`nameEn` AS `nameEn`,`stap`.`surnameEn` AS `surnameEn`,`stap`.`programCode` AS `programCode`,`stap`.`programNameTh` AS `programNameTh`,`stap`.`programNameEn` AS `programNameEn`,`stap`.`facultyID` AS `facultyID`,`stap`.`facultyNameTh` AS `facultyNameTh`,`stap`.`facultyNameEn` AS `facultyNameEn`,`stap`.`levelNameSTh` AS `levelNameSTh`,`stap`.`levelNameSEn` AS `levelNameSEn`,`stap`.`levelID` AS `levelID`,`stap`.`levelName` AS `levelName`,`stap`.`admitAcadYear` AS `admitAcadYear`,`stap`.`status` AS `status`,`stap`.`statusName` AS `statusName`,`stap`.`gender` AS `gender`,`stap`.`graduateDate` AS `graduateDate`,`stap`.`citizenID` AS `citizenID`,`stap`.`std_api_update` AS `std_api_update`,`stap`.`std_api_status` AS `std_api_status`,`stst`.`std_studentCode` AS `std_studentCode`,`stst`.`std_prenameTh` AS `std_prenameTh`,`stst`.`std_nameTh` AS `std_nameTh`,`stst`.`std_surnameTh` AS `std_surnameTh`,`stst`.`std_programNameTh` AS `std_programNameTh`,`stst`.`std_facultyNameTh` AS `std_facultyNameTh`,`stst`.`std_levelNameSTh` AS `std_levelNameSTh`,`stst`.`std_mobilephone` AS `std_mobilephone`,`stst`.`std_address` AS `std_address`,`stst`.`std_subdistrict` AS `std_subdistrict`,`stst`.`std_district` AS `std_district`,`stst`.`std_province` AS `std_province`,`stst`.`std_zip` AS `std_zip`,`stst`.`std_homephone` AS `std_homephone`,`stst`.`std_homeprovinceid` AS `std_homeprovinceid`,`stst`.`std_update` AS `std_update`,`stst`.`std_status` AS `std_status` from (`alumni`.`student_api` `stap` join `alumni`.`student_std` `stst` on(`stst`.`std_studentCode` = `stap`.`studentCode`)) group by `stap`.`studentCode` order by `stap`.`studentCode` desc
mariadb-version=100419
