TYPE=VIEW
query=select `alco`.`alumni_citizenid` AS `alumni_citizenid`,`alco`.`alumni_studentid` AS `alumni_studentid`,`alco`.`alumni_email` AS `alumni_email`,`alco`.`alumni_phone` AS `alumni_phone`,`alco`.`alumni_address` AS `alumni_address`,`alco`.`alumni_subdistrict` AS `alumni_subdistrict`,`alco`.`alumni_district` AS `alumni_district`,`alco`.`alumni_province` AS `alumni_province`,`alco`.`alumni_zip` AS `alumni_zip`,`stap`.`nameTh` AS `nameTh`,`stap`.`surnameTh` AS `surnameTh`,`stap`.`nameEn` AS `nameEn`,`stap`.`surnameEn` AS `surnameEn`,`stap`.`programCode` AS `programCode`,`stap`.`programNameTh` AS `programNameTh`,`stap`.`programNameEn` AS `programNameEn`,`stap`.`facultyID` AS `facultyID`,`stap`.`facultyNameTh` AS `facultyNameTh`,`stap`.`facultyNameEn` AS `facultyNameEn`,`stap`.`levelNameSTh` AS `levelNameSTh`,`stap`.`levelNameSEn` AS `levelNameSEn`,`stap`.`levelID` AS `levelID`,`stap`.`levelName` AS `levelName`,`stap`.`admitAcadYear` AS `admitAcadYear`,`stap`.`status` AS `status`,`stap`.`statusName` AS `statusName`,`stap`.`gender` AS `gender`,`stap`.`graduateDate` AS `graduateDate`,`stap`.`citizenID` AS `citizenID`,`stap`.`std_api_update` AS `std_api_update`,`stap`.`std_api_status` AS `std_api_status` from (`alumni`.`alumni_contact` `alco` left join `alumni`.`student_api` `stap` on(`stap`.`studentCode` = `alco`.`alumni_studentid`)) where `alco`.`alumni_status` = \'enable\'
md5=9a8b158cdf49235d59ae96db98fac68e
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-10-21 02:29:24
create-version=2
source=Select\n    alco.alumni_citizenid,\n    alco.alumni_studentid,\n    alco.alumni_email,\n    alco.alumni_phone,\n    alco.alumni_address,\n    alco.alumni_subdistrict,\n    alco.alumni_district,\n    alco.alumni_province,\n    alco.alumni_zip,\n    stap.nameTh,\n    stap.surnameTh,\n    stap.nameEn,\n    stap.surnameEn,\n    stap.programCode,\n    stap.programNameTh,\n    stap.programNameEn,\n    stap.facultyID,\n    stap.facultyNameTh,\n    stap.facultyNameEn,\n    stap.levelNameSTh,\n    stap.levelNameSEn,\n    stap.levelID,\n    stap.levelName,\n    stap.admitAcadYear,\n    stap.status,\n    stap.statusName,\n    stap.gender,\n    stap.graduateDate,\n    stap.citizenID,\n    stap.std_api_update,\n    stap.std_api_status\nFrom\n    alumni_contact alco Left Join\n    student_api stap On stap.studentCode = alco.alumni_studentid\nWhere\n    alco.alumni_status = \'enable\'
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `alco`.`alumni_citizenid` AS `alumni_citizenid`,`alco`.`alumni_studentid` AS `alumni_studentid`,`alco`.`alumni_email` AS `alumni_email`,`alco`.`alumni_phone` AS `alumni_phone`,`alco`.`alumni_address` AS `alumni_address`,`alco`.`alumni_subdistrict` AS `alumni_subdistrict`,`alco`.`alumni_district` AS `alumni_district`,`alco`.`alumni_province` AS `alumni_province`,`alco`.`alumni_zip` AS `alumni_zip`,`stap`.`nameTh` AS `nameTh`,`stap`.`surnameTh` AS `surnameTh`,`stap`.`nameEn` AS `nameEn`,`stap`.`surnameEn` AS `surnameEn`,`stap`.`programCode` AS `programCode`,`stap`.`programNameTh` AS `programNameTh`,`stap`.`programNameEn` AS `programNameEn`,`stap`.`facultyID` AS `facultyID`,`stap`.`facultyNameTh` AS `facultyNameTh`,`stap`.`facultyNameEn` AS `facultyNameEn`,`stap`.`levelNameSTh` AS `levelNameSTh`,`stap`.`levelNameSEn` AS `levelNameSEn`,`stap`.`levelID` AS `levelID`,`stap`.`levelName` AS `levelName`,`stap`.`admitAcadYear` AS `admitAcadYear`,`stap`.`status` AS `status`,`stap`.`statusName` AS `statusName`,`stap`.`gender` AS `gender`,`stap`.`graduateDate` AS `graduateDate`,`stap`.`citizenID` AS `citizenID`,`stap`.`std_api_update` AS `std_api_update`,`stap`.`std_api_status` AS `std_api_status` from (`alumni`.`alumni_contact` `alco` left join `alumni`.`student_api` `stap` on(`stap`.`studentCode` = `alco`.`alumni_studentid`)) where `alco`.`alumni_status` = \'enable\'
mariadb-version=100419
