TYPE=VIEW
query=select `dormstore`.`store_item`.`sitem_id` AS `sitem_id`,`dormstore`.`store_item`.`sitem_code` AS `sitem_code`,`dormstore`.`store_item`.`sitem_barcode` AS `sitem_barcode`,`dormstore`.`store_item`.`sitem_name` AS `sitem_name`,`dormstore`.`store_item`.`sitem_detail` AS `sitem_detail`,`dormstore`.`store_item`.`cate_id` AS `cate_id`,`dormstore`.`store_item`.`sitem_status` AS `sitem_status`,`dormstore`.`store_item_detail`.`sidetail_qty` AS `sidetail_qty`,`dormstore`.`store_item_detail`.`sidetail_price` AS `sidetail_price`,`dormstore`.`unit`.`unit_name` AS `unit_name`,`dormstore`.`unit`.`sub_unit_id` AS `sub_unit_id`,`dormstore`.`unit`.`sub_unit_multiply` AS `sub_unit_multiply`,`dormstore`.`category`.`category_name` AS `category_name` from (((`dormstore`.`store_item` left join `dormstore`.`store_item_detail` on(`dormstore`.`store_item`.`sitem_id` = `dormstore`.`store_item_detail`.`sitem_id`)) left join `dormstore`.`unit` on(`dormstore`.`unit`.`unit_id` = `dormstore`.`store_item_detail`.`unit_id`)) left join `dormstore`.`category` on(`dormstore`.`store_item`.`cate_id` = `dormstore`.`category`.`category_id`))
md5=c02a5a89d6252c744f597e87631e5e65
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2022-08-23 02:59:30
create-version=2
source=select `store_item`.`sitem_id` AS `sitem_id`,`store_item`.`sitem_code` AS `sitem_code`,`store_item`.`sitem_barcode` AS `sitem_barcode`,`store_item`.`sitem_name` AS `sitem_name`,`store_item`.`sitem_detail` AS `sitem_detail`,`store_item`.`cate_id` AS `cate_id`,`store_item`.`sitem_status` AS `sitem_status`,`store_item_detail`.`sidetail_qty` AS `sidetail_qty`,`store_item_detail`.`sidetail_price` AS `sidetail_price`,`unit`.`unit_name` AS `unit_name`,`unit`.`sub_unit_id` AS `sub_unit_id`,`unit`.`sub_unit_multiply` AS `sub_unit_multiply`,`category`.`category_name` AS `category_name` from (((`store_item` left join `store_item_detail` on((`store_item`.`sitem_id` = `store_item_detail`.`sitem_id`))) left join `unit` on((`unit`.`unit_id` = `store_item_detail`.`unit_id`))) left join `category` on((`store_item`.`cate_id` = `category`.`category_id`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `dormstore`.`store_item`.`sitem_id` AS `sitem_id`,`dormstore`.`store_item`.`sitem_code` AS `sitem_code`,`dormstore`.`store_item`.`sitem_barcode` AS `sitem_barcode`,`dormstore`.`store_item`.`sitem_name` AS `sitem_name`,`dormstore`.`store_item`.`sitem_detail` AS `sitem_detail`,`dormstore`.`store_item`.`cate_id` AS `cate_id`,`dormstore`.`store_item`.`sitem_status` AS `sitem_status`,`dormstore`.`store_item_detail`.`sidetail_qty` AS `sidetail_qty`,`dormstore`.`store_item_detail`.`sidetail_price` AS `sidetail_price`,`dormstore`.`unit`.`unit_name` AS `unit_name`,`dormstore`.`unit`.`sub_unit_id` AS `sub_unit_id`,`dormstore`.`unit`.`sub_unit_multiply` AS `sub_unit_multiply`,`dormstore`.`category`.`category_name` AS `category_name` from (((`dormstore`.`store_item` left join `dormstore`.`store_item_detail` on(`dormstore`.`store_item`.`sitem_id` = `dormstore`.`store_item_detail`.`sitem_id`)) left join `dormstore`.`unit` on(`dormstore`.`unit`.`unit_id` = `dormstore`.`store_item_detail`.`unit_id`)) left join `dormstore`.`category` on(`dormstore`.`store_item`.`cate_id` = `dormstore`.`category`.`category_id`))
mariadb-version=100419
