TYPE=VIEW
query=select `cui`.`cuisine_id` AS `cuisine_id`,`cui`.`cuisine_name` AS `cuisine_name`,`cui`.`cuisine_image` AS `cuisine_image`,`cui`.`cuisine_detail` AS `cuisine_detail`,`cui`.`cuisine_active` AS `cuisine_active`,`cui`.`cuisine_pickup` AS `cuisine_pickup`,`cui`.`cuisine_status` AS `cuisine_status`,`cui`.`cuisine_editor` AS `cuisine_editor`,`cui`.`cuisine_add_date` AS `cuisine_add_date`,`cui`.`cuisine_lastupdate` AS `cuisine_lastupdate`,`kinthai`.`dish`.`dish_id` AS `dish_id`,`kinthai`.`dish`.`cuisine_id` AS `cuisine_id1`,`kinthai`.`dish`.`dish_name` AS `dish_name`,`kinthai`.`dish`.`dish_image` AS `dish_image`,`kinthai`.`dish`.`dish_ingredients` AS `dish_ingredients`,`kinthai`.`dish`.`dish_choice` AS `dish_choice`,`kinthai`.`dish`.`dish_10_discount` AS `dish_10_discount`,`kinthai`.`dish`.`dish_min_quantity` AS `dish_min_quantity`,`kinthai`.`dish`.`dish_type` AS `dish_type`,`kinthai`.`dish`.`dish_available` AS `dish_available`,`kinthai`.`dish`.`dish_best_seller` AS `dish_best_seller`,`kinthai`.`dish`.`dish_active` AS `dish_active`,`kinthai`.`dish`.`dish_status` AS `dish_status`,`kinthai`.`dish`.`dish_editor` AS `dish_editor`,`kinthai`.`dish`.`dish_add_date` AS `dish_add_date`,`kinthai`.`dish`.`dish_lastupdate` AS `dish_lastupdate` from (`kinthai`.`cuisine` `cui` join `kinthai`.`dish` on(`kinthai`.`dish`.`cuisine_id` = `cui`.`cuisine_id`))
md5=3bdc9312e4c46f583c86cc478d552808
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2022-04-26 04:31:12
create-version=2
source=Select\n    cui.cuisine_id,\n    cui.cuisine_name,\n    cui.cuisine_image,\n    cui.cuisine_detail,\n    cui.cuisine_active,\n    cui.cuisine_pickup,\n    cui.cuisine_status,\n    cui.cuisine_editor,\n    cui.cuisine_add_date,\n    cui.cuisine_lastupdate,\n    dish.dish_id,\n    dish.cuisine_id As cuisine_id1,\n    dish.dish_name,\n    dish.dish_image,\n    dish.dish_ingredients,\n    dish.dish_choice,\n    dish.dish_10_discount,\n    dish.dish_min_quantity,\n    dish.dish_type,\n    dish.dish_available,\n    dish.dish_best_seller,\n    dish.dish_active,\n    dish.dish_status,\n    dish.dish_editor,\n    dish.dish_add_date,\n    dish.dish_lastupdate\nFrom\n    cuisine cui Inner Join\n    dish dish On dish.cuisine_id = cui.cuisine_id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cui`.`cuisine_id` AS `cuisine_id`,`cui`.`cuisine_name` AS `cuisine_name`,`cui`.`cuisine_image` AS `cuisine_image`,`cui`.`cuisine_detail` AS `cuisine_detail`,`cui`.`cuisine_active` AS `cuisine_active`,`cui`.`cuisine_pickup` AS `cuisine_pickup`,`cui`.`cuisine_status` AS `cuisine_status`,`cui`.`cuisine_editor` AS `cuisine_editor`,`cui`.`cuisine_add_date` AS `cuisine_add_date`,`cui`.`cuisine_lastupdate` AS `cuisine_lastupdate`,`kinthai`.`dish`.`dish_id` AS `dish_id`,`kinthai`.`dish`.`cuisine_id` AS `cuisine_id1`,`kinthai`.`dish`.`dish_name` AS `dish_name`,`kinthai`.`dish`.`dish_image` AS `dish_image`,`kinthai`.`dish`.`dish_ingredients` AS `dish_ingredients`,`kinthai`.`dish`.`dish_choice` AS `dish_choice`,`kinthai`.`dish`.`dish_10_discount` AS `dish_10_discount`,`kinthai`.`dish`.`dish_min_quantity` AS `dish_min_quantity`,`kinthai`.`dish`.`dish_type` AS `dish_type`,`kinthai`.`dish`.`dish_available` AS `dish_available`,`kinthai`.`dish`.`dish_best_seller` AS `dish_best_seller`,`kinthai`.`dish`.`dish_active` AS `dish_active`,`kinthai`.`dish`.`dish_status` AS `dish_status`,`kinthai`.`dish`.`dish_editor` AS `dish_editor`,`kinthai`.`dish`.`dish_add_date` AS `dish_add_date`,`kinthai`.`dish`.`dish_lastupdate` AS `dish_lastupdate` from (`kinthai`.`cuisine` `cui` join `kinthai`.`dish` on(`kinthai`.`dish`.`cuisine_id` = `cui`.`cuisine_id`))
mariadb-version=100419
