TYPE=VIEW
query=select `jou`.`jour_id` AS `jour_id`,`jou`.`jour_owner_citizenid` AS `citizenid`,`jou`.`jour_owner_prename` AS `prename`,`jou`.`jour_owner_firstname` AS `firstname`,`jou`.`jour_owner_lastname` AS `lastname`,`jou`.`department_name` AS `department_name`,`jou`.`jour_ratio` AS `ratio`,`jou`.`jour_study` AS `jour_study`,`jou`.`jour_tier` AS `jour_tier`,`jou`.`jour_journal` AS `jour_journal`,`jou`.`jour_value` AS `jour_value`,`jou`.`jour_volume_issue` AS `jour_volume_issue`,`jou`.`jour_page` AS `jour_page`,`jou`.`jour_link` AS `jour_link`,`jou`.`jour_date_avaliable` AS `jour_date_avaliable`,`jou`.`jour_fiscalyear` AS `jour_fiscalyear`,`jou`.`jour_attach` AS `jour_attach`,`jou`.`jour_detail` AS `jour_detail`,`jou`.`jour_notes` AS `jour_notes`,`jou`.`jour_status` AS `jour_status`,`jou`.`jour_create_datetime` AS `jour_create_datetime`,`jou`.`jour_editor` AS `jour_editor`,`jou`.`jour_lastupdate` AS `jour_lastupdate` from `econ_research`.`journal` `jou` where `jou`.`jour_status` = \'enable\' union select `cowo`.`cow_status` AS `cow_status`,`jou`.`jour_id` AS `jour_id`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`cowo`.`cow_ratio` AS `ratio`,`jou`.`jour_study` AS `jour_study`,`jou`.`jour_tier` AS `jour_tier`,`jou`.`jour_journal` AS `jour_journal`,`jou`.`jour_value` AS `jour_value`,`jou`.`jour_volume_issue` AS `jour_volume_issue`,`jou`.`jour_page` AS `jour_page`,`jou`.`jour_link` AS `jour_link`,`jou`.`jour_date_avaliable` AS `jour_date_avaliable`,`jou`.`jour_fiscalyear` AS `jour_fiscalyear`,`jou`.`jour_attach` AS `jour_attach`,`jou`.`jour_detail` AS `jour_detail`,`jou`.`jour_notes` AS `jour_notes`,`cowo`.`cow_create_datetime` AS `cow_create_datetime`,`cowo`.`cow_editor` AS `cow_editor`,`cowo`.`cow_lastupdate` AS `cow_lastupdate` from (`econ_research`.`journal` `jou` left join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `jou`.`jour_id`)) where `cowo`.`cow_status` = \'enable\' and `cowo`.`cow_ref_table` = \'journal\'
md5=0e370908bc4a7ea96428d9dcf022943a
updatable=0
algorithm=0
definer_user=econ_research
definer_host=%
suid=1
with_check_option=0
timestamp=2022-01-31 07:16:40
create-version=2
source=Select\n    jou.jour_id As jour_id,\n    jou.jour_owner_citizenid As citizenid,\n    jou.jour_owner_prename As prename,\n    jou.jour_owner_firstname As firstname,\n    jou.jour_owner_lastname As lastname,\n    jou.department_name As department_name,\n    jou.jour_ratio As ratio,\n    jou.jour_study As jour_study,\n    jou.jour_tier As jour_tier,\n    jou.jour_journal As jour_journal,\n    jou.jour_value As jour_value,\n    jou.jour_volume_issue As jour_volume_issue,\n    jou.jour_page As jour_page,\n    jou.jour_link As jour_link,\n    jou.jour_date_avaliable As jour_date_avaliable,\n    jou.jour_fiscalyear As jour_fiscalyear,\n    jou.jour_attach As jour_attach,\n    jou.jour_detail As jour_detail,\n    jou.jour_notes As jour_notes,\n    jou.jour_status As jour_status,\n    jou.jour_create_datetime As jour_create_datetime,\n    jou.jour_editor As jour_editor,\n    jou.jour_lastupdate As jour_lastupdate\nFrom\n    journal jou\nWhere\n    jou.jour_status = \'enable\'\nunion\nSelect\n    cowo.cow_status As cow_status,\n    jou.jour_id As jour_id,\n    cowo.cow_citizenid As citizenid,\n    cowo.cow_prename As prename,\n    cowo.cow_firstname As firstname,\n    cowo.cow_lastname As lastname,\n    cowo.department_name As department_name,\n    cowo.cow_ratio As ratio,\n    jou.jour_study As jour_study,\n    jou.jour_tier As jour_tier,\n    jou.jour_journal As jour_journal,\n    jou.jour_value As jour_value,\n    jou.jour_volume_issue As jour_volume_issue,\n    jou.jour_page As jour_page,\n    jou.jour_link As jour_link,\n    jou.jour_date_avaliable As jour_date_avaliable,\n    jou.jour_fiscalyear As jour_fiscalyear,\n    jou.jour_attach As jour_attach,\n    jou.jour_detail As jour_detail,\n    jou.jour_notes As jour_notes,\n    cowo.cow_create_datetime As cow_create_datetime,\n    cowo.cow_editor As cow_editor,\n    cowo.cow_lastupdate As cow_lastupdate\nFrom\n    journal jou Left Join\n    co_worker cowo On cowo.cow_ref_id = jou.jour_id\nWhere\n    cowo.cow_status = \'enable\' And\n    cowo.cow_ref_table = \'journal\'
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `jou`.`jour_id` AS `jour_id`,`jou`.`jour_owner_citizenid` AS `citizenid`,`jou`.`jour_owner_prename` AS `prename`,`jou`.`jour_owner_firstname` AS `firstname`,`jou`.`jour_owner_lastname` AS `lastname`,`jou`.`department_name` AS `department_name`,`jou`.`jour_ratio` AS `ratio`,`jou`.`jour_study` AS `jour_study`,`jou`.`jour_tier` AS `jour_tier`,`jou`.`jour_journal` AS `jour_journal`,`jou`.`jour_value` AS `jour_value`,`jou`.`jour_volume_issue` AS `jour_volume_issue`,`jou`.`jour_page` AS `jour_page`,`jou`.`jour_link` AS `jour_link`,`jou`.`jour_date_avaliable` AS `jour_date_avaliable`,`jou`.`jour_fiscalyear` AS `jour_fiscalyear`,`jou`.`jour_attach` AS `jour_attach`,`jou`.`jour_detail` AS `jour_detail`,`jou`.`jour_notes` AS `jour_notes`,`jou`.`jour_status` AS `jour_status`,`jou`.`jour_create_datetime` AS `jour_create_datetime`,`jou`.`jour_editor` AS `jour_editor`,`jou`.`jour_lastupdate` AS `jour_lastupdate` from `econ_research`.`journal` `jou` where `jou`.`jour_status` = \'enable\' union select `cowo`.`cow_status` AS `cow_status`,`jou`.`jour_id` AS `jour_id`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`cowo`.`cow_ratio` AS `ratio`,`jou`.`jour_study` AS `jour_study`,`jou`.`jour_tier` AS `jour_tier`,`jou`.`jour_journal` AS `jour_journal`,`jou`.`jour_value` AS `jour_value`,`jou`.`jour_volume_issue` AS `jour_volume_issue`,`jou`.`jour_page` AS `jour_page`,`jou`.`jour_link` AS `jour_link`,`jou`.`jour_date_avaliable` AS `jour_date_avaliable`,`jou`.`jour_fiscalyear` AS `jour_fiscalyear`,`jou`.`jour_attach` AS `jour_attach`,`jou`.`jour_detail` AS `jour_detail`,`jou`.`jour_notes` AS `jour_notes`,`cowo`.`cow_create_datetime` AS `cow_create_datetime`,`cowo`.`cow_editor` AS `cow_editor`,`cowo`.`cow_lastupdate` AS `cow_lastupdate` from (`econ_research`.`journal` `jou` left join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `jou`.`jour_id`)) where `cowo`.`cow_status` = \'enable\' and `cowo`.`cow_ref_table` = \'journal\'
mariadb-version=100419
