TYPE=VIEW
query=select `pro`.`pro_id` AS `pro_id`,`pro`.`pro_owner_citizenid` AS `citizenid`,`pro`.`pro_owner_prename` AS `prename`,`pro`.`pro_owner_firstname` AS `firstname`,`pro`.`pro_owner_lastname` AS `lastname`,`pro`.`department_name` AS `department_name`,`pro`.`pro_ratio` AS `pro_ratio`,`pro`.`pro_study` AS `pro_study`,`pro`.`pro_conf` AS `pro_conf`,`pro`.`pro_conf_owner` AS `pro_conf_owner`,`pro`.`pro_location` AS `pro_location`,`pro`.`pro_date_begin` AS `pro_date_begin`,`pro`.`pro_date_end` AS `pro_date_end`,`pro`.`pro_volume_issue` AS `pro_volume_issue`,`pro`.`pro_page` AS `pro_page`,`pro`.`pro_link` AS `pro_link`,`pro`.`pro_tier` AS `pro_tier`,`pro`.`pro_fiscalyear` AS `pro_fiscalyear`,`pro`.`pro_attach` AS `pro_attach`,`pro`.`pro_detail` AS `pro_detail`,`pro`.`pro_notes` AS `pro_notes`,`pro`.`pro_create_datetitme` AS `pro_create_datetitme`,`pro`.`pro_status` AS `pro_status`,`pro`.`pro_editor` AS `pro_editor`,`pro`.`pro_lastupdate` AS `pro_lastupdate` from `econ_research`.`proceeding` `pro` where `pro`.`pro_status` = \'enable\' union select `pro`.`pro_id` AS `pro_id`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`cowo`.`cow_ratio` AS `cow_ratio`,`pro`.`pro_study` AS `pro_study`,`pro`.`pro_conf` AS `pro_conf`,`pro`.`pro_conf_owner` AS `pro_conf_owner`,`pro`.`pro_location` AS `pro_location`,`pro`.`pro_date_begin` AS `pro_date_begin`,`pro`.`pro_date_end` AS `pro_date_end`,`pro`.`pro_volume_issue` AS `pro_volume_issue`,`pro`.`pro_page` AS `pro_page`,`pro`.`pro_link` AS `pro_link`,`pro`.`pro_tier` AS `pro_tier`,`pro`.`pro_fiscalyear` AS `pro_fiscalyear`,`pro`.`pro_attach` AS `pro_attach`,`pro`.`pro_detail` AS `pro_detail`,`pro`.`pro_notes` AS `pro_notes`,`cowo`.`cow_create_datetime` AS `cow_create_datetime`,`cowo`.`cow_status` AS `cow_status`,`cowo`.`cow_editor` AS `cow_editor`,`cowo`.`cow_lastupdate` AS `cow_lastupdate` from (`econ_research`.`proceeding` `pro` left join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `pro`.`pro_id`)) where `cowo`.`cow_status` = \'enable\' and `cowo`.`cow_ref_table` = \'proceeding\'
md5=e045ed9e5426c704bfcc11119db0bef5
updatable=0
algorithm=0
definer_user=econ_research
definer_host=%
suid=1
with_check_option=0
timestamp=2022-01-31 07:17:19
create-version=2
source=select `pro`.`pro_id` AS `pro_id`,`pro`.`pro_owner_citizenid` AS `citizenid`,`pro`.`pro_owner_prename` AS `prename`,`pro`.`pro_owner_firstname` AS `firstname`,`pro`.`pro_owner_lastname` AS `lastname`,`pro`.`department_name` AS `department_name`,`pro`.`pro_ratio` AS `pro_ratio`,`pro`.`pro_study` AS `pro_study`,`pro`.`pro_conf` AS `pro_conf`,`pro`.`pro_conf_owner` AS `pro_conf_owner`,`pro`.`pro_location` AS `pro_location`,`pro`.`pro_date_begin` AS `pro_date_begin`,`pro`.`pro_date_end` AS `pro_date_end`,`pro`.`pro_volume_issue` AS `pro_volume_issue`,`pro`.`pro_page` AS `pro_page`,`pro`.`pro_link` AS `pro_link`,`pro`.`pro_tier` AS `pro_tier`,`pro`.`pro_fiscalyear` AS `pro_fiscalyear`,`pro`.`pro_attach` AS `pro_attach`,`pro`.`pro_detail` AS `pro_detail`,`pro`.`pro_notes` AS `pro_notes`,`pro`.`pro_create_datetitme` AS `pro_create_datetitme`,`pro`.`pro_status` AS `pro_status`,`pro`.`pro_editor` AS `pro_editor`,`pro`.`pro_lastupdate` AS `pro_lastupdate` from `econ_research`.`proceeding` `pro` where `pro`.`pro_status` = \'enable\' union select `pro`.`pro_id` AS `pro_id`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`cowo`.`cow_ratio` AS `cow_ratio`,`pro`.`pro_study` AS `pro_study`,`pro`.`pro_conf` AS `pro_conf`,`pro`.`pro_conf_owner` AS `pro_conf_owner`,`pro`.`pro_location` AS `pro_location`,`pro`.`pro_date_begin` AS `pro_date_begin`,`pro`.`pro_date_end` AS `pro_date_end`,`pro`.`pro_volume_issue` AS `pro_volume_issue`,`pro`.`pro_page` AS `pro_page`,`pro`.`pro_link` AS `pro_link`,`pro`.`pro_tier` AS `pro_tier`,`pro`.`pro_fiscalyear` AS `pro_fiscalyear`,`pro`.`pro_attach` AS `pro_attach`,`pro`.`pro_detail` AS `pro_detail`,`pro`.`pro_notes` AS `pro_notes`,`cowo`.`cow_create_datetime` AS `cow_create_datetime`,`cowo`.`cow_status` AS `cow_status`,`cowo`.`cow_editor` AS `cow_editor`,`cowo`.`cow_lastupdate` AS `cow_lastupdate` from (`econ_research`.`proceeding` `pro` left join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `pro`.`pro_id`)) where `cowo`.`cow_status` = \'enable\' and `cowo`.`cow_ref_table` = \'proceeding\'
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `pro`.`pro_id` AS `pro_id`,`pro`.`pro_owner_citizenid` AS `citizenid`,`pro`.`pro_owner_prename` AS `prename`,`pro`.`pro_owner_firstname` AS `firstname`,`pro`.`pro_owner_lastname` AS `lastname`,`pro`.`department_name` AS `department_name`,`pro`.`pro_ratio` AS `pro_ratio`,`pro`.`pro_study` AS `pro_study`,`pro`.`pro_conf` AS `pro_conf`,`pro`.`pro_conf_owner` AS `pro_conf_owner`,`pro`.`pro_location` AS `pro_location`,`pro`.`pro_date_begin` AS `pro_date_begin`,`pro`.`pro_date_end` AS `pro_date_end`,`pro`.`pro_volume_issue` AS `pro_volume_issue`,`pro`.`pro_page` AS `pro_page`,`pro`.`pro_link` AS `pro_link`,`pro`.`pro_tier` AS `pro_tier`,`pro`.`pro_fiscalyear` AS `pro_fiscalyear`,`pro`.`pro_attach` AS `pro_attach`,`pro`.`pro_detail` AS `pro_detail`,`pro`.`pro_notes` AS `pro_notes`,`pro`.`pro_create_datetitme` AS `pro_create_datetitme`,`pro`.`pro_status` AS `pro_status`,`pro`.`pro_editor` AS `pro_editor`,`pro`.`pro_lastupdate` AS `pro_lastupdate` from `econ_research`.`proceeding` `pro` where `pro`.`pro_status` = \'enable\' union select `pro`.`pro_id` AS `pro_id`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`cowo`.`cow_ratio` AS `cow_ratio`,`pro`.`pro_study` AS `pro_study`,`pro`.`pro_conf` AS `pro_conf`,`pro`.`pro_conf_owner` AS `pro_conf_owner`,`pro`.`pro_location` AS `pro_location`,`pro`.`pro_date_begin` AS `pro_date_begin`,`pro`.`pro_date_end` AS `pro_date_end`,`pro`.`pro_volume_issue` AS `pro_volume_issue`,`pro`.`pro_page` AS `pro_page`,`pro`.`pro_link` AS `pro_link`,`pro`.`pro_tier` AS `pro_tier`,`pro`.`pro_fiscalyear` AS `pro_fiscalyear`,`pro`.`pro_attach` AS `pro_attach`,`pro`.`pro_detail` AS `pro_detail`,`pro`.`pro_notes` AS `pro_notes`,`cowo`.`cow_create_datetime` AS `cow_create_datetime`,`cowo`.`cow_status` AS `cow_status`,`cowo`.`cow_editor` AS `cow_editor`,`cowo`.`cow_lastupdate` AS `cow_lastupdate` from (`econ_research`.`proceeding` `pro` left join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `pro`.`pro_id`)) where `cowo`.`cow_status` = \'enable\' and `cowo`.`cow_ref_table` = \'proceeding\'
mariadb-version=100419
