TYPE=VIEW
query=select `res`.`res_id` AS `res_id`,`res`.`res_researchID` AS `res_researchID`,`res`.`res_researchCode` AS `res_researchCode`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`cowo`.`cow_ratio` AS `ratio`,`res`.`res_name` AS `res_name`,`res`.`res_period_begin` AS `res_period_begin`,`res`.`res_period_finish` AS `res_period_finish`,`res`.`res_fiscalyear` AS `res_fiscalyear`,`res`.`res_budget_source` AS `res_budget_source`,`res`.`res_budget` AS `res_budget`,`res`.`res_budget_province` AS `res_budget_province`,`res`.`res_tier` AS `res_tier`,`res`.`res_attach` AS `res_attach`,`res`.`res_detail` AS `res_detail`,`res`.`res_notes` AS `res_notes`,`cowo`.`cow_create_datetime` AS `create_datetime`,`cowo`.`cow_status` AS `res_status`,`cowo`.`cow_editor` AS `res_editor`,`cowo`.`cow_lastupdate` AS `res_lastupdate` from (`econ_research`.`research` `res` left join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `res`.`res_id`)) where `cowo`.`cow_ref_table` = \'research\' union all select `econ_research`.`research`.`res_id` AS `res_id`,`econ_research`.`research`.`res_researchID` AS `res_researchID`,`econ_research`.`research`.`res_researchCode` AS `res_researchCode`,`econ_research`.`research`.`res_owner_citizenid` AS `res_owner_citizenid`,`econ_research`.`research`.`res_owner_prename` AS `res_owner_prename`,`econ_research`.`research`.`res_owner_firstname` AS `res_owner_firstname`,`econ_research`.`research`.`res_owner_lastname` AS `res_owner_lastname`,`econ_research`.`research`.`department_name` AS `department_name`,`econ_research`.`research`.`res_ratio` AS `res_ratio`,`econ_research`.`research`.`res_name` AS `res_name`,`econ_research`.`research`.`res_period_begin` AS `res_period_begin`,`econ_research`.`research`.`res_period_finish` AS `res_period_finish`,`econ_research`.`research`.`res_fiscalyear` AS `res_fiscalyear`,`econ_research`.`research`.`res_budget_source` AS `res_budget_source`,`econ_research`.`research`.`res_budget` AS `res_budget`,`econ_research`.`research`.`res_budget_province` AS `res_budget_province`,`econ_research`.`research`.`res_tier` AS `res_tier`,`econ_research`.`research`.`res_attach` AS `res_attach`,`econ_research`.`research`.`res_detail` AS `res_detail`,`econ_research`.`research`.`res_notes` AS `res_notes`,`econ_research`.`research`.`res_create_datetime` AS `res_create_datetime`,`econ_research`.`research`.`res_status` AS `res_status`,`econ_research`.`research`.`res_editor` AS `res_editor`,`econ_research`.`research`.`res_lastupdate` AS `res_lastupdate` from `econ_research`.`research`
md5=69bcc3ffa19f057256ddbfb9988c0e6f
updatable=0
algorithm=0
definer_user=econ_research
definer_host=%
suid=1
with_check_option=0
timestamp=2022-02-02 11:13:48
create-version=2
source=SELECT\n    res.res_id,\n    res.res_researchID,\n    res.res_researchCode,\n    cowo.cow_citizenid AS citizenid,\n    cowo.cow_prename AS prename,\n    cowo.cow_firstname AS firstname,\n    cowo.cow_lastname AS lastname,\n    cowo.department_name AS department_name,\n    cowo.cow_ratio AS ratio,\n    res.res_name,\n    res.res_period_begin,\n    res.res_period_finish,\n    res.res_fiscalyear,\n    res.res_budget_source,\n    res.res_budget,\n    res.res_budget_province,\n    res.res_tier,\n    res.res_attach,\n    res.res_detail,\n    res.res_notes,\n    cowo.cow_create_datetime AS create_datetime,\n    cowo.cow_status AS res_status,\n    cowo.cow_editor AS res_editor,\n    cowo.cow_lastupdate AS res_lastupdate\nFROM\n    research res\nLEFT JOIN co_worker cowo ON\n    cowo.cow_ref_id = res.res_id\nWHERE\n    cowo.cow_ref_table = \'research\'\nUNION ALL\nSELECT\n    research.res_id,\n    research.res_researchID,\n    research.res_researchCode,\n    research.res_owner_citizenid,\n    research.res_owner_prename,\n    research.res_owner_firstname,\n    research.res_owner_lastname,\n    research.department_name,\n    research.res_ratio,\n    research.res_name,\n    research.res_period_begin,\n    research.res_period_finish,\n    research.res_fiscalyear,\n    research.res_budget_source,\n    research.res_budget,\n    research.res_budget_province,\n    research.res_tier,\n    research.res_attach,\n    research.res_detail,\n    research.res_notes,\n    research.res_create_datetime,\n    research.res_status,\n    research.res_editor,\n    research.res_lastupdate\nFROM\n    research
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `res`.`res_id` AS `res_id`,`res`.`res_researchID` AS `res_researchID`,`res`.`res_researchCode` AS `res_researchCode`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`cowo`.`cow_ratio` AS `ratio`,`res`.`res_name` AS `res_name`,`res`.`res_period_begin` AS `res_period_begin`,`res`.`res_period_finish` AS `res_period_finish`,`res`.`res_fiscalyear` AS `res_fiscalyear`,`res`.`res_budget_source` AS `res_budget_source`,`res`.`res_budget` AS `res_budget`,`res`.`res_budget_province` AS `res_budget_province`,`res`.`res_tier` AS `res_tier`,`res`.`res_attach` AS `res_attach`,`res`.`res_detail` AS `res_detail`,`res`.`res_notes` AS `res_notes`,`cowo`.`cow_create_datetime` AS `create_datetime`,`cowo`.`cow_status` AS `res_status`,`cowo`.`cow_editor` AS `res_editor`,`cowo`.`cow_lastupdate` AS `res_lastupdate` from (`econ_research`.`research` `res` left join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `res`.`res_id`)) where `cowo`.`cow_ref_table` = \'research\' union all select `econ_research`.`research`.`res_id` AS `res_id`,`econ_research`.`research`.`res_researchID` AS `res_researchID`,`econ_research`.`research`.`res_researchCode` AS `res_researchCode`,`econ_research`.`research`.`res_owner_citizenid` AS `res_owner_citizenid`,`econ_research`.`research`.`res_owner_prename` AS `res_owner_prename`,`econ_research`.`research`.`res_owner_firstname` AS `res_owner_firstname`,`econ_research`.`research`.`res_owner_lastname` AS `res_owner_lastname`,`econ_research`.`research`.`department_name` AS `department_name`,`econ_research`.`research`.`res_ratio` AS `res_ratio`,`econ_research`.`research`.`res_name` AS `res_name`,`econ_research`.`research`.`res_period_begin` AS `res_period_begin`,`econ_research`.`research`.`res_period_finish` AS `res_period_finish`,`econ_research`.`research`.`res_fiscalyear` AS `res_fiscalyear`,`econ_research`.`research`.`res_budget_source` AS `res_budget_source`,`econ_research`.`research`.`res_budget` AS `res_budget`,`econ_research`.`research`.`res_budget_province` AS `res_budget_province`,`econ_research`.`research`.`res_tier` AS `res_tier`,`econ_research`.`research`.`res_attach` AS `res_attach`,`econ_research`.`research`.`res_detail` AS `res_detail`,`econ_research`.`research`.`res_notes` AS `res_notes`,`econ_research`.`research`.`res_create_datetime` AS `res_create_datetime`,`econ_research`.`research`.`res_status` AS `res_status`,`econ_research`.`research`.`res_editor` AS `res_editor`,`econ_research`.`research`.`res_lastupdate` AS `res_lastupdate` from `econ_research`.`research`
mariadb-version=100419
