TYPE=VIEW
query=select `res`.`res_id` AS `res_id`,`res`.`res_researchID` AS `res_researchID`,`res`.`res_researchCode` AS `res_researchCode`,`res`.`res_owner_citizenid` AS `citizenid`,`res`.`res_owner_prename` AS `prename`,`res`.`res_owner_firstname` AS `firstname`,`res`.`res_owner_lastname` AS `lastname`,`res`.`department_name` AS `department_name`,`res`.`res_name` AS `res_name`,`res`.`res_ratio` AS `res_ratio`,`res`.`res_period_begin` AS `res_period_begin`,`res`.`res_period_finish` AS `res_period_finish`,`res`.`res_fiscalyear` AS `res_fiscalyear`,`res`.`res_budget_source` AS `res_budget_source`,`res`.`res_budget` AS `res_budget`,`res`.`res_budget_province` AS `res_budget_province`,`res`.`res_tier` AS `res_tier`,`res`.`res_attach` AS `res_attach`,`res`.`res_detail` AS `res_detail`,`res`.`res_notes` AS `res_notes`,`res`.`res_create_datetime` AS `res_create_datetime`,`res`.`res_status` AS `res_status`,`res`.`res_editor` AS `res_editor`,`res`.`res_lastupdate` AS `res_lastupdate` from `econ_research`.`research` `res` union all select `res`.`res_id` AS `res_id`,`res`.`res_researchID` AS `res_researchID`,`res`.`res_researchCode` AS `res_researchCode`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`res`.`res_name` AS `res_name`,`cowo`.`cow_ratio` AS `cow_ratio`,`res`.`res_period_begin` AS `res_period_begin`,`res`.`res_period_finish` AS `res_period_finish`,`res`.`res_fiscalyear` AS `res_fiscalyear`,`res`.`res_budget_source` AS `res_budget_source`,`res`.`res_budget` AS `res_budget`,`res`.`res_budget_province` AS `res_budget_province`,`res`.`res_tier` AS `res_tier`,`res`.`res_attach` AS `res_attach`,`res`.`res_detail` AS `res_detail`,`res`.`res_notes` AS `res_notes`,`cowo`.`cow_create_datetime` AS `cow_create_datetime`,`cowo`.`cow_status` AS `cow_status`,`cowo`.`cow_editor` AS `cow_editor`,`cowo`.`cow_lastupdate` AS `cow_lastupdate` from (`econ_research`.`research` `res` join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `res`.`res_id`)) where `cowo`.`cow_ref_table` = \'research\'
md5=52cbbe60d8ab4d5fc50326896b98550c
updatable=0
algorithm=0
definer_user=econ_research
definer_host=%
suid=1
with_check_option=0
timestamp=2022-01-31 07:17:51
create-version=2
source=Select\n    res.res_id,\n    res.res_researchID,\n    res.res_researchCode,\n    res.res_owner_citizenid As citizenid,\n    res.res_owner_prename As prename,\n    res.res_owner_firstname As firstname,\n    res.res_owner_lastname As lastname,\n    res.department_name,\n    res.res_name,\n    res.res_ratio,\n    res.res_period_begin,\n    res.res_period_finish,\n    res.res_fiscalyear,\n    res.res_budget_source,\n    res.res_budget,\n    res.res_budget_province,\n    res.res_tier,\n    res.res_attach,\n    res.res_detail,\n    res.res_notes,\n    res.res_create_datetime,\n    res.res_status,\n    res.res_editor,\n    res.res_lastupdate\nFrom\n    research res\nunion All\nSelect\n    res.res_id,\n    res.res_researchID,\n    res.res_researchCode,\n    cowo.cow_citizenid As citizenid,\n    cowo.cow_prename As prename,\n    cowo.cow_firstname As firstname,\n    cowo.cow_lastname As lastname,\n    cowo.department_name,\n    res.res_name,\n    cowo.cow_ratio,\n    res.res_period_begin,\n    res.res_period_finish,\n    res.res_fiscalyear,\n    res.res_budget_source,\n    res.res_budget,\n    res.res_budget_province,\n    res.res_tier,\n    res.res_attach,\n    res.res_detail,\n    res.res_notes,\n    cowo.cow_create_datetime,\n    cowo.cow_status,\n    cowo.cow_editor,\n    cowo.cow_lastupdate\nFrom\n    research res Join\n    co_worker cowo On cowo.cow_ref_id = res.res_id\nWhere\n    cowo.cow_ref_table = \'research\'
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `res`.`res_id` AS `res_id`,`res`.`res_researchID` AS `res_researchID`,`res`.`res_researchCode` AS `res_researchCode`,`res`.`res_owner_citizenid` AS `citizenid`,`res`.`res_owner_prename` AS `prename`,`res`.`res_owner_firstname` AS `firstname`,`res`.`res_owner_lastname` AS `lastname`,`res`.`department_name` AS `department_name`,`res`.`res_name` AS `res_name`,`res`.`res_ratio` AS `res_ratio`,`res`.`res_period_begin` AS `res_period_begin`,`res`.`res_period_finish` AS `res_period_finish`,`res`.`res_fiscalyear` AS `res_fiscalyear`,`res`.`res_budget_source` AS `res_budget_source`,`res`.`res_budget` AS `res_budget`,`res`.`res_budget_province` AS `res_budget_province`,`res`.`res_tier` AS `res_tier`,`res`.`res_attach` AS `res_attach`,`res`.`res_detail` AS `res_detail`,`res`.`res_notes` AS `res_notes`,`res`.`res_create_datetime` AS `res_create_datetime`,`res`.`res_status` AS `res_status`,`res`.`res_editor` AS `res_editor`,`res`.`res_lastupdate` AS `res_lastupdate` from `econ_research`.`research` `res` union all select `res`.`res_id` AS `res_id`,`res`.`res_researchID` AS `res_researchID`,`res`.`res_researchCode` AS `res_researchCode`,`cowo`.`cow_citizenid` AS `citizenid`,`cowo`.`cow_prename` AS `prename`,`cowo`.`cow_firstname` AS `firstname`,`cowo`.`cow_lastname` AS `lastname`,`cowo`.`department_name` AS `department_name`,`res`.`res_name` AS `res_name`,`cowo`.`cow_ratio` AS `cow_ratio`,`res`.`res_period_begin` AS `res_period_begin`,`res`.`res_period_finish` AS `res_period_finish`,`res`.`res_fiscalyear` AS `res_fiscalyear`,`res`.`res_budget_source` AS `res_budget_source`,`res`.`res_budget` AS `res_budget`,`res`.`res_budget_province` AS `res_budget_province`,`res`.`res_tier` AS `res_tier`,`res`.`res_attach` AS `res_attach`,`res`.`res_detail` AS `res_detail`,`res`.`res_notes` AS `res_notes`,`cowo`.`cow_create_datetime` AS `cow_create_datetime`,`cowo`.`cow_status` AS `cow_status`,`cowo`.`cow_editor` AS `cow_editor`,`cowo`.`cow_lastupdate` AS `cow_lastupdate` from (`econ_research`.`research` `res` join `econ_research`.`co_worker` `cowo` on(`cowo`.`cow_ref_id` = `res`.`res_id`)) where `cowo`.`cow_ref_table` = \'research\'
mariadb-version=100419
