TYPE=VIEW
query=select `cap`.`cap_id` AS `cap_id`,`cap`.`cap_notes` AS `cap_notes`,`cap`.`cap_semester` AS `cap_semester`,`cap`.`cap_year` AS `cap_year`,`cap`.`course_id` AS `course_id`,`cap`.`cap_department` AS `cap_department`,`faed_teachingload`.`course`.`course_code_th` AS `course_code_th`,`faed_teachingload`.`course`.`course_code_en` AS `course_code_en`,`faed_teachingload`.`course`.`course_name_th` AS `course_name_th`,`faed_teachingload`.`course`.`course_name_en` AS `course_name_en`,`faed_teachingload`.`course`.`course_studio` AS `course_studio`,`faed_teachingload`.`course`.`course_credit` AS `course_credit`,`faed_teachingload`.`course`.`course_lec` AS `course_lec`,`faed_teachingload`.`course`.`course_lab` AS `course_lab`,`faed_teachingload`.`course`.`course_self` AS `course_self`,`faed_teachingload`.`course`.`course_lec_hrs` AS `course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs` AS `course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs` AS `course_self_hrs`,`cap`.`cap_citizenid` AS `cap_citizenid`,`telo`.`teaching_load_titlePosition` AS `teaching_load_titlePosition`,`telo`.`teaching_load_firstName` AS `teaching_load_firstName`,`telo`.`teaching_load_lastName` AS `teaching_load_lastName`,`telo`.`teaching_load_department` AS `teaching_load_department`,`cap`.`cap_lecture_hours` AS `cap_lecture_hours`,`cap`.`cap_lab_hours` AS `cap_lab_hours`,`cap`.`cap_self_hours` AS `cap_self_hours` from ((`faed_teachingload`.`course_active_primary` `cap` left join `faed_teachingload`.`course` on(`faed_teachingload`.`course`.`course_id` = `cap`.`course_id`)) left join `faed_teachingload`.`teaching_load` `telo` on(`cap`.`cap_citizenid` = `telo`.`teaching_load_citizenid`)) where `faed_teachingload`.`course`.`course_status` = \'enable\' and `cap`.`cap_status` = \'enable\' group by `cap`.`cap_id`,`cap`.`cap_notes`,`cap`.`cap_semester`,`cap`.`cap_year`,`cap`.`course_id`,`cap`.`cap_department`,`faed_teachingload`.`course`.`course_code_th`,`faed_teachingload`.`course`.`course_code_en`,`faed_teachingload`.`course`.`course_name_th`,`faed_teachingload`.`course`.`course_name_en`,`faed_teachingload`.`course`.`course_credit`,`faed_teachingload`.`course`.`course_lec`,`faed_teachingload`.`course`.`course_lab`,`faed_teachingload`.`course`.`course_self`,`faed_teachingload`.`course`.`course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs`,`cap`.`cap_citizenid`,`telo`.`teaching_load_titlePosition`,`telo`.`teaching_load_firstName`,`telo`.`teaching_load_lastName`,`telo`.`teaching_load_department`,`cap`.`cap_lecture_hours`,`cap`.`cap_lab_hours`,`cap`.`cap_self_hours` order by `cap`.`cap_id`
md5=b9d8032420c441baafbee8c8db11f099
updatable=0
algorithm=0
definer_user=teachingload
definer_host=%
suid=1
with_check_option=0
timestamp=2022-03-31 07:44:31
create-version=2
source=select `cap`.`cap_id` AS `cap_id`,`cap`.`cap_notes` AS `cap_notes`,`cap`.`cap_semester` AS `cap_semester`,`cap`.`cap_year` AS `cap_year`,`cap`.`course_id` AS `course_id`,`cap`.`cap_department` AS `cap_department`,`faed_teachingload`.`course`.`course_code_th` AS `course_code_th`,`faed_teachingload`.`course`.`course_code_en` AS `course_code_en`,`faed_teachingload`.`course`.`course_name_th` AS `course_name_th`,`faed_teachingload`.`course`.`course_name_en` AS `course_name_en`,`faed_teachingload`.`course`.`course_studio` AS `course_studio`,`faed_teachingload`.`course`.`course_credit` AS `course_credit`,`faed_teachingload`.`course`.`course_lec` AS `course_lec`,`faed_teachingload`.`course`.`course_lab` AS `course_lab`,`faed_teachingload`.`course`.`course_self` AS `course_self`,`faed_teachingload`.`course`.`course_lec_hrs` AS `course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs` AS `course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs` AS `course_self_hrs`,`cap`.`cap_citizenid` AS `cap_citizenid`,`telo`.`teaching_load_titlePosition` AS `teaching_load_titlePosition`,`telo`.`teaching_load_firstName` AS `teaching_load_firstName`,`telo`.`teaching_load_lastName` AS `teaching_load_lastName`,`telo`.`teaching_load_department` AS `teaching_load_department`,`cap`.`cap_lecture_hours` AS `cap_lecture_hours`,`cap`.`cap_lab_hours` AS `cap_lab_hours`,`cap`.`cap_self_hours` AS `cap_self_hours` from ((`faed_teachingload`.`course_active_primary` `cap` left join `faed_teachingload`.`course` on(`faed_teachingload`.`course`.`course_id` = `cap`.`course_id`)) left join `faed_teachingload`.`teaching_load` `telo` on(`cap`.`cap_citizenid` = `telo`.`teaching_load_citizenid`)) where `faed_teachingload`.`course`.`course_status` = \'enable\' and `cap`.`cap_status` = \'enable\' group by `cap`.`cap_id`,`cap`.`cap_notes`,`cap`.`cap_semester`,`cap`.`cap_year`,`cap`.`course_id`,`cap`.`cap_department`,`faed_teachingload`.`course`.`course_code_th`,`faed_teachingload`.`course`.`course_code_en`,`faed_teachingload`.`course`.`course_name_th`,`faed_teachingload`.`course`.`course_name_en`,`faed_teachingload`.`course`.`course_credit`,`faed_teachingload`.`course`.`course_lec`,`faed_teachingload`.`course`.`course_lab`,`faed_teachingload`.`course`.`course_self`,`faed_teachingload`.`course`.`course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs`,`cap`.`cap_citizenid`,`telo`.`teaching_load_titlePosition`,`telo`.`teaching_load_firstName`,`telo`.`teaching_load_lastName`,`telo`.`teaching_load_department`,`cap`.`cap_lecture_hours`,`cap`.`cap_lab_hours`,`cap`.`cap_self_hours` order by `cap`.`cap_id`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cap`.`cap_id` AS `cap_id`,`cap`.`cap_notes` AS `cap_notes`,`cap`.`cap_semester` AS `cap_semester`,`cap`.`cap_year` AS `cap_year`,`cap`.`course_id` AS `course_id`,`cap`.`cap_department` AS `cap_department`,`faed_teachingload`.`course`.`course_code_th` AS `course_code_th`,`faed_teachingload`.`course`.`course_code_en` AS `course_code_en`,`faed_teachingload`.`course`.`course_name_th` AS `course_name_th`,`faed_teachingload`.`course`.`course_name_en` AS `course_name_en`,`faed_teachingload`.`course`.`course_studio` AS `course_studio`,`faed_teachingload`.`course`.`course_credit` AS `course_credit`,`faed_teachingload`.`course`.`course_lec` AS `course_lec`,`faed_teachingload`.`course`.`course_lab` AS `course_lab`,`faed_teachingload`.`course`.`course_self` AS `course_self`,`faed_teachingload`.`course`.`course_lec_hrs` AS `course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs` AS `course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs` AS `course_self_hrs`,`cap`.`cap_citizenid` AS `cap_citizenid`,`telo`.`teaching_load_titlePosition` AS `teaching_load_titlePosition`,`telo`.`teaching_load_firstName` AS `teaching_load_firstName`,`telo`.`teaching_load_lastName` AS `teaching_load_lastName`,`telo`.`teaching_load_department` AS `teaching_load_department`,`cap`.`cap_lecture_hours` AS `cap_lecture_hours`,`cap`.`cap_lab_hours` AS `cap_lab_hours`,`cap`.`cap_self_hours` AS `cap_self_hours` from ((`faed_teachingload`.`course_active_primary` `cap` left join `faed_teachingload`.`course` on(`faed_teachingload`.`course`.`course_id` = `cap`.`course_id`)) left join `faed_teachingload`.`teaching_load` `telo` on(`cap`.`cap_citizenid` = `telo`.`teaching_load_citizenid`)) where `faed_teachingload`.`course`.`course_status` = \'enable\' and `cap`.`cap_status` = \'enable\' group by `cap`.`cap_id`,`cap`.`cap_notes`,`cap`.`cap_semester`,`cap`.`cap_year`,`cap`.`course_id`,`cap`.`cap_department`,`faed_teachingload`.`course`.`course_code_th`,`faed_teachingload`.`course`.`course_code_en`,`faed_teachingload`.`course`.`course_name_th`,`faed_teachingload`.`course`.`course_name_en`,`faed_teachingload`.`course`.`course_credit`,`faed_teachingload`.`course`.`course_lec`,`faed_teachingload`.`course`.`course_lab`,`faed_teachingload`.`course`.`course_self`,`faed_teachingload`.`course`.`course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs`,`cap`.`cap_citizenid`,`telo`.`teaching_load_titlePosition`,`telo`.`teaching_load_firstName`,`telo`.`teaching_load_lastName`,`telo`.`teaching_load_department`,`cap`.`cap_lecture_hours`,`cap`.`cap_lab_hours`,`cap`.`cap_self_hours` order by `cap`.`cap_id`
mariadb-version=100419
