TYPE=VIEW
query=select `cap`.`cap_id` AS `cap_id`,`cap`.`cap_notes` AS `cap_notes`,`cap`.`cap_semester` AS `cap_semester`,`cap`.`cap_year` AS `cap_year`,`cap`.`course_id` AS `course_id`,`faed_teachingload`.`course`.`course_code_th` AS `course_code_th`,`faed_teachingload`.`course`.`course_code_en` AS `course_code_en`,`faed_teachingload`.`course`.`course_name_th` AS `course_name_th`,`faed_teachingload`.`course`.`course_name_en` AS `course_name_en`,`faed_teachingload`.`course`.`course_credit` AS `course_credit`,`faed_teachingload`.`course`.`course_lec` AS `course_lec`,`faed_teachingload`.`course`.`course_lab` AS `course_lab`,`faed_teachingload`.`course`.`course_self` AS `course_self`,`faed_teachingload`.`course`.`course_lec_hrs` AS `course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs` AS `course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs` AS `course_self_hrs`,`cap`.`cap_citizenid` AS `cap_citizenid`,`telo`.`teaching_load_titlePosition` AS `teaching_load_titlePosition`,`telo`.`teaching_load_firstName` AS `teaching_load_firstName`,`telo`.`teaching_load_lastName` AS `teaching_load_lastName`,`cap`.`cap_lecture_hours` AS `cap_lecture_hours`,`cap`.`cap_lab_hours` AS `cap_lab_hours`,`cap`.`cap_self_hours` AS `cap_self_hours` from ((`faed_teachingload`.`course_active_primary` `cap` left join `faed_teachingload`.`course` on(`faed_teachingload`.`course`.`course_id` = `cap`.`course_id`)) left join `faed_teachingload`.`teaching_load` `telo` on(`cap`.`cap_citizenid` = `telo`.`teaching_load_citizenid`)) where `faed_teachingload`.`course`.`course_status` = \'enable\' and `cap`.`cap_status` = \'enable\' group by `cap`.`cap_id`,`cap`.`cap_notes`,`cap`.`cap_semester`,`cap`.`cap_year`,`cap`.`course_id`,`faed_teachingload`.`course`.`course_code_th`,`faed_teachingload`.`course`.`course_code_en`,`faed_teachingload`.`course`.`course_name_th`,`faed_teachingload`.`course`.`course_name_en`,`faed_teachingload`.`course`.`course_credit`,`faed_teachingload`.`course`.`course_lec`,`faed_teachingload`.`course`.`course_lab`,`faed_teachingload`.`course`.`course_self`,`faed_teachingload`.`course`.`course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs`,`cap`.`cap_citizenid`,`telo`.`teaching_load_titlePosition`,`telo`.`teaching_load_firstName`,`telo`.`teaching_load_lastName`,`cap`.`cap_lecture_hours`,`cap`.`cap_lab_hours`,`cap`.`cap_self_hours` order by `cap`.`cap_id`
md5=bdc8b2f8b97e3e5f636c8565879803c5
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2022-03-01 04:33:51
create-version=2
source=SELECT\n    cap.cap_id AS cap_id,\n    cap.cap_notes AS cap_notes,\n    cap.cap_semester AS cap_semester,\n    cap.cap_year AS cap_year,\n    cap.course_id AS course_id,\n    course.course_code_th AS course_code_th,\n    course.course_code_en AS course_code_en,\n    course.course_name_th AS course_name_th,\n    course.course_name_en AS course_name_en,\n    course.course_credit AS course_credit,\n    course.course_lec AS course_lec,\n    course.course_lab AS course_lab,\n    course.course_self AS course_self,\n    course.course_lec_hrs AS course_lec_hrs,\n    course.course_lab_hrs AS course_lab_hrs,\n    course.course_self_hrs AS course_self_hrs,\n    cap.cap_citizenid AS cap_citizenid,\n    telo.teaching_load_titlePosition,\n    telo.teaching_load_firstName,\n    telo.teaching_load_lastName,\n    cap.cap_lecture_hours AS cap_lecture_hours,\n    cap.cap_lab_hours AS cap_lab_hours,\n    cap.cap_self_hours AS cap_self_hours\nFROM\n    course_active_primary cap\nLEFT JOIN course ON course.course_id = cap.course_id\nLEFT JOIN teaching_load telo ON\n    cap.cap_citizenid = telo.teaching_load_citizenid\nWHERE\n    course.course_status = \'enable\' AND cap.cap_status = \'enable\'\nGROUP BY\n    cap.cap_id,\n    cap.cap_notes,\n    cap.cap_semester,\n    cap.cap_year,\n    cap.course_id,\n    course.course_code_th,\n    course.course_code_en,\n    course.course_name_th,\n    course.course_name_en,\n    course.course_credit,\n    course.course_lec,\n    course.course_lab,\n    course.course_self,\n    course.course_lec_hrs,\n    course.course_lab_hrs,\n    course.course_self_hrs,\n    cap.cap_citizenid,\n    telo.teaching_load_titlePosition,\n    telo.teaching_load_firstName,\n    telo.teaching_load_lastName,\n    cap.cap_lecture_hours,\n    cap.cap_lab_hours,\n    cap.cap_self_hours\nORDER BY\n    cap_id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cap`.`cap_id` AS `cap_id`,`cap`.`cap_notes` AS `cap_notes`,`cap`.`cap_semester` AS `cap_semester`,`cap`.`cap_year` AS `cap_year`,`cap`.`course_id` AS `course_id`,`faed_teachingload`.`course`.`course_code_th` AS `course_code_th`,`faed_teachingload`.`course`.`course_code_en` AS `course_code_en`,`faed_teachingload`.`course`.`course_name_th` AS `course_name_th`,`faed_teachingload`.`course`.`course_name_en` AS `course_name_en`,`faed_teachingload`.`course`.`course_credit` AS `course_credit`,`faed_teachingload`.`course`.`course_lec` AS `course_lec`,`faed_teachingload`.`course`.`course_lab` AS `course_lab`,`faed_teachingload`.`course`.`course_self` AS `course_self`,`faed_teachingload`.`course`.`course_lec_hrs` AS `course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs` AS `course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs` AS `course_self_hrs`,`cap`.`cap_citizenid` AS `cap_citizenid`,`telo`.`teaching_load_titlePosition` AS `teaching_load_titlePosition`,`telo`.`teaching_load_firstName` AS `teaching_load_firstName`,`telo`.`teaching_load_lastName` AS `teaching_load_lastName`,`cap`.`cap_lecture_hours` AS `cap_lecture_hours`,`cap`.`cap_lab_hours` AS `cap_lab_hours`,`cap`.`cap_self_hours` AS `cap_self_hours` from ((`faed_teachingload`.`course_active_primary` `cap` left join `faed_teachingload`.`course` on(`faed_teachingload`.`course`.`course_id` = `cap`.`course_id`)) left join `faed_teachingload`.`teaching_load` `telo` on(`cap`.`cap_citizenid` = `telo`.`teaching_load_citizenid`)) where `faed_teachingload`.`course`.`course_status` = \'enable\' and `cap`.`cap_status` = \'enable\' group by `cap`.`cap_id`,`cap`.`cap_notes`,`cap`.`cap_semester`,`cap`.`cap_year`,`cap`.`course_id`,`faed_teachingload`.`course`.`course_code_th`,`faed_teachingload`.`course`.`course_code_en`,`faed_teachingload`.`course`.`course_name_th`,`faed_teachingload`.`course`.`course_name_en`,`faed_teachingload`.`course`.`course_credit`,`faed_teachingload`.`course`.`course_lec`,`faed_teachingload`.`course`.`course_lab`,`faed_teachingload`.`course`.`course_self`,`faed_teachingload`.`course`.`course_lec_hrs`,`faed_teachingload`.`course`.`course_lab_hrs`,`faed_teachingload`.`course`.`course_self_hrs`,`cap`.`cap_citizenid`,`telo`.`teaching_load_titlePosition`,`telo`.`teaching_load_firstName`,`telo`.`teaching_load_lastName`,`cap`.`cap_lecture_hours`,`cap`.`cap_lab_hours`,`cap`.`cap_self_hours` order by `cap`.`cap_id`
mariadb-version=100419
